// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIjNk9XByVM2QnBWFvPdCj2F97g8JU6Ec',
    appId: '1:980285770883:web:127d92e5f251de0e6d5fb6',
    messagingSenderId: '980285770883',
    projectId: 'mobile-computing-project-a864c',
    authDomain: 'mobile-computing-project-a864c.firebaseapp.com',
    storageBucket: 'mobile-computing-project-a864c.firebasestorage.app',
    measurementId: 'G-8C0T0ERGGN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMVfb7WLMMKCdiUndS_EBN2sAjKq_x53E',
    appId: '1:980285770883:android:71ba297e95f034246d5fb6',
    messagingSenderId: '980285770883',
    projectId: 'mobile-computing-project-a864c',
    storageBucket: 'mobile-computing-project-a864c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_gly7BGnKt0sO1K8I4EQucoRoA4DACTQ',
    appId: '1:980285770883:ios:0e5c6ada294f5b296d5fb6',
    messagingSenderId: '980285770883',
    projectId: 'mobile-computing-project-a864c',
    storageBucket: 'mobile-computing-project-a864c.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_gly7BGnKt0sO1K8I4EQucoRoA4DACTQ',
    appId: '1:980285770883:ios:0e5c6ada294f5b296d5fb6',
    messagingSenderId: '980285770883',
    projectId: 'mobile-computing-project-a864c',
    storageBucket: 'mobile-computing-project-a864c.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIjNk9XByVM2QnBWFvPdCj2F97g8JU6Ec',
    appId: '1:980285770883:web:8bba942077f5d3dc6d5fb6',
    messagingSenderId: '980285770883',
    projectId: 'mobile-computing-project-a864c',
    authDomain: 'mobile-computing-project-a864c.firebaseapp.com',
    storageBucket: 'mobile-computing-project-a864c.firebasestorage.app',
    measurementId: 'G-700D25VZT8',
  );
}
